version: '3'

services:
  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 7080:5432
    container_name: docker-compose-db-alter-application
    volumes:
      - ./db:/var/lib/postgresql/data

  alter-application-backend:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-compose-alter-application-backend
    restart: always
    ports:
      - 7081:3101
    environment:
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_URL: ${POSTGRES_URL}
      SENDGRID_FROM_EMAIL: ${SENDGRID_FROM_EMAIL}
      SENDGRID_REMINDER_EMAIL_TEMPLATE: ${SENDGRID_REMINDER_EMAIL_TEMPLATE}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
